"""The generated header registry stays in sync with shared/headers.json.

markback/_headers.py is generated by scripts/gen_headers.py from
shared/headers.json (issue #13 — one source of truth for headers across the
Python and JS libraries). These tests fail if the generated module drifts from
the source, or if the writer stops emitting headers in the registry's order.
"""

import json
from pathlib import Path

from markback import _headers
from markback.types import Action, FileRef, Record
from markback.writer import write_record_canonical

SOURCE = Path(__file__).parent.parent / "shared" / "headers.json"


def _source():
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def test_known_headers_match_source():
    assert _headers.KNOWN_HEADERS == set(_source()["known"])


def test_canonical_order_matches_source():
    assert _headers.CANONICAL_ORDER == _source()["canonical_order"]


def test_section_inherited_matches_source():
    assert _headers.SECTION_INHERITED == set(_source()["section_inherited"])


def test_v1_map_matches_source():
    assert _headers.V1_HEADER_MAP == _source()["v1_map"]


def test_writer_emits_headers_in_canonical_order():
    # A record that carries every header; the emitted header lines must follow
    # CANONICAL_ORDER exactly.
    record = Record(
        feedback="fb",
        id="the-id",
        reply_to="parent",
        by="alice",
        file=FileRef("./x.py"),
        input=FileRef("./p.txt"),
        tags=["t1"],
        actions=[Action(verb="created", timestamp="2026-07-25T00:00:00Z", actor=None)],
        content="some inline content",
    )
    out = write_record_canonical(record, prefer_compact=False)
    emitted = [line.split()[0][1:] for line in out.splitlines() if line.startswith("@")]
    expected = [h for h in _headers.CANONICAL_ORDER]
    assert emitted == expected
